/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/car_scene.glb 
Author: toivo (https://sketchfab.com/toivo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/car-scene-b7b32eaca80d460c9338197e2c9d1408
Title: Car Scene
*/

import { useGLTF } from "@react-three/drei";

export function CarScene(props: any) {
  const { nodes, materials } = useGLTF("/car-snow/car_scene.glb") as any;
  return (
    <group {...props} dispose={null}>
      <group position={[40.507, 74.477, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.car_body_body_0.geometry}
          material={materials.body}
        />
        <mesh
          geometry={nodes.car_body_rubber_0.geometry}
          material={materials.rubber}
        />
        <mesh
          geometry={nodes.car_body_glass_0.geometry}
          material={materials.glass}
        />
      </group>
      <group
        position={[60.954, 50.964, 72.077]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <mesh
          geometry={nodes.door_left_body_0.geometry}
          material={materials.body}
        />
        <mesh
          geometry={nodes.door_left_rubber_0.geometry}
          material={materials.rubber}
        />
        <mesh
          geometry={nodes.door_left_interior_0.geometry}
          material={materials.interior}
        />
      </group>
      <group position={[55.23, 73.302, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.interior_01_interior_0.geometry}
          material={materials.interior}
        />
        <mesh
          geometry={nodes.interior_01_chrome_0.geometry}
          material={materials.chrome}
        />
      </group>
      <group
        position={[-25.659, 75.44, 30.097]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <mesh
          geometry={nodes.interior_00_interior_0.geometry}
          material={materials.interior}
        />
        <mesh
          geometry={nodes.interior_00_chrome_0.geometry}
          material={materials.chrome}
        />
      </group>
      <group
        position={[60.961, 52.352, -71.876]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <mesh
          geometry={nodes.door_right_body_0.geometry}
          material={materials.body}
        />
        <mesh
          geometry={nodes.door_right_rubber_0.geometry}
          material={materials.rubber}
        />
        <mesh
          geometry={nodes.door_right_interior_0.geometry}
          material={materials.interior}
        />
      </group>
      <group
        position={[-6.27, 101.334, -57.266]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <mesh
          geometry={nodes.glass_02_body_0.geometry}
          material={materials.body}
        />
        <mesh
          geometry={nodes.glass_02_glass_0.geometry}
          material={materials.glass}
        />
      </group>
      <group
        position={[-5.875, 101.292, 57.084]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <mesh
          geometry={nodes.glass_03_glass_0.geometry}
          material={materials.glass}
        />
        <mesh
          geometry={nodes.glass_03_body_0.geometry}
          material={materials.body}
        />
      </group>
      <group
        position={[34.563, 137.34, 11.035]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group position={[0.042, -0.071, 16.302]} rotation={[0, 0, -1.92]}>
          <mesh
            geometry={nodes.chest_top_chest_0.geometry}
            material={materials.chest}
            position={[21.348, -41.938, -2.121]}
          />
        </group>
        <mesh
          geometry={nodes.chest_base_chest_0.geometry}
          material={materials.chest}
        />
      </group>
      {/* <group
        position={[54.766, -2.068, -284.313]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group position={[0.007, 0.078, 199.335]}>
          <mesh
            geometry={
              nodes.vintage_lantern_glass_7_lantern_wall_glass_1_0.geometry
            }
            material={materials.lantern_wall_glass_1}
            position={[0.238, -7.28, 149.232]}
          />
          <mesh
            geometry={nodes.vintage_lantern_7_lantern_wall_base_1_0.geometry}
            material={materials.lantern_wall_base_1}
          />
        </group>
        <mesh
          geometry={nodes.vintage_lantern_7_base_lantern_wall_base_2_0.geometry}
          material={materials.lantern_wall_base_2}
        />
      </group> */}
      <mesh
        geometry={nodes.hood_body_0.geometry}
        material={materials.body}
        position={[-82.966, 75.292, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.rear_bumper_body_0.geometry}
        material={materials.body}
        position={[196.328, 31.597, -0.163]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.viper_01_body_0.geometry}
        material={materials.body}
        position={[-35.738, 93.998, 7.389]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.viper_02_body_0.geometry}
        material={materials.body}
        position={[-34.358, 93.066, -32.945]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.front_bumper_body_0.geometry}
        material={materials.body}
        position={[-114.745, 31.894, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.number_plate_number_0.geometry}
        material={materials.number}
        position={[-122.792, 32.206, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.bottom_body_0.geometry}
        material={materials.body}
        position={[42.377, 36.238, 0.003]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.wheel_00_wheels_0.geometry}
        material={materials.wheels}
        position={[-71.898, 25.337, 62.764]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.wheel_01_wheels_0.geometry}
        material={materials.wheels}
        position={[130.144, 25.337, 62.555]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.wheel_02_wheels_0.geometry}
        material={materials.wheels}
        position={[130.144, 25.337, -59.22]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.wheel_03_wheels_0.geometry}
        material={materials.wheels}
        position={[-71.26, 25.337, -59.22]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.back_door_body_0.geometry}
        material={materials.body}
        position={[178.277, 63.436, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.lights_00_lights_0.geometry}
        material={materials.lights}
        position={[-113.307, 58.243, -52.905]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.railings_body_0.geometry}
        material={materials.body}
        position={[61.596, 132.744, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.logo_01_body_0.geometry}
        material={materials.body}
        position={[-118.585, 66.188, 0.491]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.lights_01_lights_0.geometry}
        material={materials.lights}
        position={[-111.181, 42.634, 56.291]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.lights_02_lights_0.geometry}
        material={materials.lights}
        position={[-111.181, 42.634, -56.291]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.lights_03_lights_0.geometry}
        material={materials.lights}
        position={[-95.614, 63.404, 66.673]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.lights_04_lights_0.geometry}
        material={materials.lights}
        position={[-95.614, 63.404, -66.673]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.lights_05_lights_0.geometry}
        material={materials.lights}
        position={[193.917, 54.699, 54.226]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.glass_01_glass_0.geometry}
        material={materials.glass}
        position={[32.163, 101.386, -57.626]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.glass_00_glass_0.geometry}
        material={materials.glass}
        position={[32.163, 101.386, 57.626]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.wheel_004_wheels_0.geometry}
        material={materials.wheels}
        position={[82.193, 145.057, 16.24]}
        rotation={[Math.PI, 0, 0]}
      />
      <mesh
        geometry={nodes.wheel_005_wheels_0.geometry}
        material={materials.wheels}
        position={[82.193, 151.168, -18.517]}
        rotation={[2.618, 0, 0]}
      />
      <mesh
        geometry={nodes.shadowplane_shadow_0.geometry}
        material={materials.shadow}
        position={[38.854, 0, 0.611]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

// useGLTF.preload("/car-snow/car_scene.glb");
